language: python
python:
  - "3.7"
install:
  - python setup.py install
  - pip install mkdocs mkdocs-material mkautodoc
  - pip install pymdown-extensions python-markdown-math
  - pip install pyspellchecker
script:
  - bin/get_cppad_py.sh system
  - bin/run_tests.sh
  - bin/extract_md.py
  - make examples
  - mkdocs build
